train_steps: 1000000/${action_repeat}
frame_stack: 3
num_channels: 32
img_size: 84
lr: 3e-4
pi_lr: 3e-4
batch_size: 512
latent_dim: 256
explore_schedule: linear(0, ${intrinsic_reward_coef}, 40000, 10000)
regularization_schedule: linear(0.05, ${mixture_coef}, 40000, 10000)