train_steps: 3000000/${action_repeat}
action_repeat: 2
iterations: 12
latent_dim: 128
explore_schedule: linear(0, ${intrinsic_reward_coef}, 1350000, 150000)
regularization_schedule: linear(0.05, ${mixture_coef}, 100000, 50000)