action_repeat: 2
episode_length: 100/${action_repeat}
train_steps: 100000/${action_repeat}
min_std: 0.05

intrinsic_reward_coef: 0.0
horizon: 6
std_schedule: linear(0.5, ${min_std}, 25000, 0)  # duration 25000 train step
horizon_schedule: linear(2, ${horizon}, 25000, 0)
explore_schedule: linear(0, ${intrinsic_reward_coef}, 5000, 5000)
regularization_schedule: linear(0.05, ${mixture_coef}, 1, 5000)

eval_freq_episodes: 20
seed_steps: 5000